steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/beerdle-frontend'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '--build-arg'
      - 'VITE_API_KEY=$_VITE_API_KEY'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/beerdle-frontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'beerdle-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/beerdle-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _VITE_API_URL: 'http://localhost:8000' # Default value, override during submit
  _VITE_API_KEY: ''                      # Default value, override during submit

images:
  - 'gcr.io/$PROJECT_ID/beerdle-frontend'
