server {
    listen       8080;
    server_name  https://beerdle-api-final-713774466210.europe-west1.run.app;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Health check endpoint for Cloud Run
    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
